[package]
name = "excel-merger"
version = "0.1.0"
edition = "2021"

[lib]
name = "app"
path = "src/app.rs"

[dependencies]
calamine = "0.16.2"
xlsxwriter = "0.6.0"
scopeguard = "1.1"
thiserror = "1.0"

[[test]]
name = "app_integration_test"
path = "tests/app_integration_test.rs"